//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ReaderInterfaceSService")]
    [System.SerializableAttribute()]
    public partial class ReadersInfos : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.ComponentModel.BindingList<ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.ReaderInfo> InfosDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.ComponentModel.BindingList<ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.ReaderInfo> InfosData
        {
            get
            {
                return this.InfosDataField;
            }
            set
            {
                this.InfosDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ReaderInterfaceSService")]
    [System.SerializableAttribute()]
    public partial class ReaderInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int A0GateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int A1GateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DownloadIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DownloadStartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReaderIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int A0GateID
        {
            get
            {
                return this.A0GateIDField;
            }
            set
            {
                this.A0GateIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int A1GateID
        {
            get
            {
                return this.A1GateIDField;
            }
            set
            {
                this.A1GateIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DownloadInterval
        {
            get
            {
                return this.DownloadIntervalField;
            }
            set
            {
                this.DownloadIntervalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DownloadStartTime
        {
            get
            {
                return this.DownloadStartTimeField;
            }
            set
            {
                this.DownloadStartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReaderID
        {
            get
            {
                return this.ReaderIDField;
            }
            set
            {
                this.ReaderIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ReaderInterfaceSService")]
    [System.SerializableAttribute()]
    public partial class ReadersStatuses : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActionReaderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlertReaderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.ReaderStatus> StatusesDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionReaderID
        {
            get
            {
                return this.ActionReaderIDField;
            }
            set
            {
                this.ActionReaderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlertReaderID
        {
            get
            {
                return this.AlertReaderIDField;
            }
            set
            {
                this.AlertReaderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.ReaderStatus> StatusesData
        {
            get
            {
                return this.StatusesDataField;
            }
            set
            {
                this.StatusesDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ReaderInterfaceSService")]
    [System.SerializableAttribute()]
    public partial class ReaderStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDataExistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDownloadingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNetExistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReaderActionDoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReaderAlertDoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MemoryOccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NextTimeDownloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReaderIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDataExist
        {
            get
            {
                return this.IsDataExistField;
            }
            set
            {
                this.IsDataExistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDownloading
        {
            get
            {
                return this.IsDownloadingField;
            }
            set
            {
                this.IsDownloadingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNetExist
        {
            get
            {
                return this.IsNetExistField;
            }
            set
            {
                this.IsNetExistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReaderActionDone
        {
            get
            {
                return this.IsReaderActionDoneField;
            }
            set
            {
                this.IsReaderActionDoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReaderAlertDone
        {
            get
            {
                return this.IsReaderAlertDoneField;
            }
            set
            {
                this.IsReaderAlertDoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemoryOccupation
        {
            get
            {
                return this.MemoryOccupationField;
            }
            set
            {
                this.MemoryOccupationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NextTimeDownload
        {
            get
            {
                return this.NextTimeDownloadField;
            }
            set
            {
                this.NextTimeDownloadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReaderID
        {
            get
            {
                return this.ReaderIDField;
            }
            set
            {
                this.ReaderIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ReaderInterfaceSService", ConfigurationName="ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.IReaderInterfaceSService")]
    public interface IReaderInterfaceSService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ReaderInterfaceSService/IReaderInterfaceSService/StartLogDownload", ReplyAction="http://ReaderInterfaceSService/IReaderInterfaceSService/StartLogDownloadResponse")]
        void StartLogDownload();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ReaderInterfaceSService/IReaderInterfaceSService/StopLogDownload", ReplyAction="http://ReaderInterfaceSService/IReaderInterfaceSService/StopLogDownloadResponse")]
        void StopLogDownload();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ReaderInterfaceSService/IReaderInterfaceSService/AbortLogDownload", ReplyAction="http://ReaderInterfaceSService/IReaderInterfaceSService/AbortLogDownloadResponse")]
        void AbortLogDownload();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ReaderInterfaceSService/IReaderInterfaceSService/ChekPrerequests", ReplyAction="http://ReaderInterfaceSService/IReaderInterfaceSService/ChekPrerequestsResponse")]
        bool ChekPrerequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ReaderInterfaceSService/IReaderInterfaceSService/GetReadersInfos", ReplyAction="http://ReaderInterfaceSService/IReaderInterfaceSService/GetReadersInfosResponse")]
        ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.ReadersInfos GetReadersInfos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ReaderInterfaceSService/IReaderInterfaceSService/GetReadersStatuses", ReplyAction="http://ReaderInterfaceSService/IReaderInterfaceSService/GetReadersStatusesResponse")]
        ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.ReadersStatuses GetReadersStatuses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ReaderInterfaceSService/IReaderInterfaceSService/SetSelectedReaders", ReplyAction="http://ReaderInterfaceSService/IReaderInterfaceSService/SetSelectedReadersResponse")]
        void SetSelectedReaders(ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.ReadersInfos selectedReaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ReaderInterfaceSService/IReaderInterfaceSService/IsLogDownloadStarted", ReplyAction="http://ReaderInterfaceSService/IReaderInterfaceSService/IsLogDownloadStartedResponse")]
        bool IsLogDownloadStarted();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IReaderControlServiceChannel : ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.IReaderInterfaceSService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ReaderInterfaceSServiceClient : System.ServiceModel.ClientBase<ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.IReaderInterfaceSService>, ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.IReaderInterfaceSService
    {
        
        public ReaderInterfaceSServiceClient()
        {
        }
        
        public ReaderInterfaceSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ReaderInterfaceSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ReaderInterfaceSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ReaderInterfaceSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void StartLogDownload()
        {
            base.Channel.StartLogDownload();
        }
        
        public void StopLogDownload()
        {
            base.Channel.StopLogDownload();
        }
        
        public void AbortLogDownload()
        {
            base.Channel.AbortLogDownload();
        }
        
        public bool ChekPrerequests()
        {
            return base.Channel.ChekPrerequests();
        }
        
        public ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.ReadersInfos GetReadersInfos()
        {
            return base.Channel.GetReadersInfos();
        }
        
        public ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.ReadersStatuses GetReadersStatuses()
        {
            return base.Channel.GetReadersStatuses();
        }
        
        public void SetSelectedReaders(ACTAReaderInterfaceSServiceWinClient.ReaderInterfaceSService.ReadersInfos selectedReaders)
        {
            base.Channel.SetSelectedReaders(selectedReaders);
        }
        
        public bool IsLogDownloadStarted()
        {
            return base.Channel.IsLogDownloadStarted();
        }
    }
}
