//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailNotificationServiceWinClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://EmailNotificationService", ConfigurationName="ServiceReference1.IEmailNotificationService")]
    public interface IEmailNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EmailNotificationService/IEmailNotificationService/StartNotification", ReplyAction="http://EmailNotificationService/IEmailNotificationService/StartNotificationRespon" +
            "se")]
        void StartNotification();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EmailNotificationService/IEmailNotificationService/StopNotification", ReplyAction="http://EmailNotificationService/IEmailNotificationService/StopNotificationRespons" +
            "e")]
        void StopNotification();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EmailNotificationService/IEmailNotificationService/GetServiceStatus", ReplyAction="http://EmailNotificationService/IEmailNotificationService/GetServiceStatusRespons" +
            "e")]
        string GetServiceStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EmailNotificationService/IEmailNotificationService/GetNotificationStatus", ReplyAction="http://EmailNotificationService/IEmailNotificationService/GetNotificationStatusRe" +
            "sponse")]
        string GetNotificationStatus();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IEmailNotificationServiceChannel : EmailNotificationServiceWinClient.ServiceReference1.IEmailNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EmailNotificationServiceClient : System.ServiceModel.ClientBase<EmailNotificationServiceWinClient.ServiceReference1.IEmailNotificationService>, EmailNotificationServiceWinClient.ServiceReference1.IEmailNotificationService {
        
        public EmailNotificationServiceClient() {
        }
        
        public EmailNotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailNotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailNotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartNotification() {
            base.Channel.StartNotification();
        }
        
        public void StopNotification() {
            base.Channel.StopNotification();
        }
        
        public string GetServiceStatus() {
            return base.Channel.GetServiceStatus();
        }
        
        public string GetNotificationStatus() {
            return base.Channel.GetNotificationStatus();
        }
    }
}
